-- =============================================
-- Shinhan AAS Server - Oracle DDL Script
-- =============================================

-- 시퀀스 생성
CREATE SEQUENCE AAS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SUBMODEL_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE CONCEPT_DESC_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- =============================================
-- AAS (Asset Administration Shell) 테이블
-- =============================================
CREATE TABLE AAS_SHELL (
    SEQ                 NUMBER(19) PRIMARY KEY,
    AAS_ID              VARCHAR2(500) NOT NULL,
    ID_SHORT            VARCHAR2(200),
    ASSET_KIND          VARCHAR2(50),
    GLOBAL_ASSET_ID     VARCHAR2(500),
    VERSION             NUMBER(10) NOT NULL,
    IS_ACTIVE           NUMBER(1) DEFAULT 1 NOT NULL,
    AAS_JSON            CLOB,
    CREATED_BY          VARCHAR2(100),
    CREATED_AT          TIMESTAMP NOT NULL,
    UPDATED_BY          VARCHAR2(100),
    UPDATED_AT          TIMESTAMP
);

-- AAS 인덱스
CREATE INDEX IDX_AAS_AAS_ID ON AAS_SHELL(AAS_ID);
CREATE INDEX IDX_AAS_IS_ACTIVE ON AAS_SHELL(IS_ACTIVE);
CREATE INDEX IDX_AAS_AAS_ID_VERSION ON AAS_SHELL(AAS_ID, VERSION);
CREATE INDEX IDX_AAS_CREATED_AT ON AAS_SHELL(CREATED_AT);

-- AAS 코멘트
COMMENT ON TABLE AAS_SHELL IS 'Asset Administration Shell 저장 테이블';
COMMENT ON COLUMN AAS_SHELL.SEQ IS '자동 증가 시퀀스';
COMMENT ON COLUMN AAS_SHELL.AAS_ID IS 'AAS 고유 식별자';
COMMENT ON COLUMN AAS_SHELL.ID_SHORT IS 'AAS 짧은 이름';
COMMENT ON COLUMN AAS_SHELL.ASSET_KIND IS '자산 종류 (INSTANCE, TYPE)';
COMMENT ON COLUMN AAS_SHELL.GLOBAL_ASSET_ID IS '글로벌 자산 ID';
COMMENT ON COLUMN AAS_SHELL.VERSION IS '버전 번호';
COMMENT ON COLUMN AAS_SHELL.IS_ACTIVE IS '활성화 여부 (1=활성, 0=비활성)';
COMMENT ON COLUMN AAS_SHELL.AAS_JSON IS 'AAS 전체 JSON 데이터';
COMMENT ON COLUMN AAS_SHELL.CREATED_BY IS '생성자';
COMMENT ON COLUMN AAS_SHELL.CREATED_AT IS '생성 일시';
COMMENT ON COLUMN AAS_SHELL.UPDATED_BY IS '수정자';
COMMENT ON COLUMN AAS_SHELL.UPDATED_AT IS '수정 일시';

-- =============================================
-- Submodel 테이블
-- =============================================
CREATE TABLE AAS_SUBMODEL (
    SEQ                 NUMBER(19) PRIMARY KEY,
    SUBMODEL_ID         VARCHAR2(500) NOT NULL,
    ID_SHORT            VARCHAR2(200),
    SEMANTIC_ID         VARCHAR2(500),
    AAS_ID              VARCHAR2(500),
    VERSION             NUMBER(10) NOT NULL,
    IS_ACTIVE           NUMBER(1) DEFAULT 1 NOT NULL,
    SUBMODEL_JSON       CLOB,
    CREATED_BY          VARCHAR2(100),
    CREATED_AT          TIMESTAMP NOT NULL,
    UPDATED_BY          VARCHAR2(100),
    UPDATED_AT          TIMESTAMP
);

-- Submodel 인덱스
CREATE INDEX IDX_SM_SUBMODEL_ID ON AAS_SUBMODEL(SUBMODEL_ID);
CREATE INDEX IDX_SM_AAS_ID ON AAS_SUBMODEL(AAS_ID);
CREATE INDEX IDX_SM_IS_ACTIVE ON AAS_SUBMODEL(IS_ACTIVE);
CREATE INDEX IDX_SM_SUBMODEL_ID_VERSION ON AAS_SUBMODEL(SUBMODEL_ID, VERSION);
CREATE INDEX IDX_SM_CREATED_AT ON AAS_SUBMODEL(CREATED_AT);

-- Submodel 코멘트
COMMENT ON TABLE AAS_SUBMODEL IS 'Submodel 저장 테이블';
COMMENT ON COLUMN AAS_SUBMODEL.SEQ IS '자동 증가 시퀀스';
COMMENT ON COLUMN AAS_SUBMODEL.SUBMODEL_ID IS 'Submodel 고유 식별자';
COMMENT ON COLUMN AAS_SUBMODEL.ID_SHORT IS 'Submodel 짧은 이름';
COMMENT ON COLUMN AAS_SUBMODEL.SEMANTIC_ID IS 'Semantic ID (의미 식별자)';
COMMENT ON COLUMN AAS_SUBMODEL.AAS_ID IS '연결된 AAS ID';
COMMENT ON COLUMN AAS_SUBMODEL.VERSION IS '버전 번호';
COMMENT ON COLUMN AAS_SUBMODEL.IS_ACTIVE IS '활성화 여부 (1=활성, 0=비활성)';
COMMENT ON COLUMN AAS_SUBMODEL.SUBMODEL_JSON IS 'Submodel 전체 JSON 데이터';
COMMENT ON COLUMN AAS_SUBMODEL.CREATED_BY IS '생성자';
COMMENT ON COLUMN AAS_SUBMODEL.CREATED_AT IS '생성 일시';
COMMENT ON COLUMN AAS_SUBMODEL.UPDATED_BY IS '수정자';
COMMENT ON COLUMN AAS_SUBMODEL.UPDATED_AT IS '수정 일시';

-- =============================================
-- ConceptDescription 테이블
-- =============================================
CREATE TABLE AAS_CONCEPT_DESCRIPTION (
    SEQ                 NUMBER(19) PRIMARY KEY,
    CD_ID               VARCHAR2(500) NOT NULL,
    ID_SHORT            VARCHAR2(200),
    VERSION             NUMBER(10) NOT NULL,
    IS_ACTIVE           NUMBER(1) DEFAULT 1 NOT NULL,
    CD_JSON             CLOB,
    CREATED_BY          VARCHAR2(100),
    CREATED_AT          TIMESTAMP NOT NULL,
    UPDATED_BY          VARCHAR2(100),
    UPDATED_AT          TIMESTAMP
);

-- ConceptDescription 인덱스
CREATE INDEX IDX_CD_CD_ID ON AAS_CONCEPT_DESCRIPTION(CD_ID);
CREATE INDEX IDX_CD_IS_ACTIVE ON AAS_CONCEPT_DESCRIPTION(IS_ACTIVE);
CREATE INDEX IDX_CD_CD_ID_VERSION ON AAS_CONCEPT_DESCRIPTION(CD_ID, VERSION);

-- ConceptDescription 코멘트
COMMENT ON TABLE AAS_CONCEPT_DESCRIPTION IS 'ConceptDescription 저장 테이블';
COMMENT ON COLUMN AAS_CONCEPT_DESCRIPTION.SEQ IS '자동 증가 시퀀스';
COMMENT ON COLUMN AAS_CONCEPT_DESCRIPTION.CD_ID IS 'ConceptDescription 고유 식별자';
COMMENT ON COLUMN AAS_CONCEPT_DESCRIPTION.ID_SHORT IS 'ConceptDescription 짧은 이름';
COMMENT ON COLUMN AAS_CONCEPT_DESCRIPTION.VERSION IS '버전 번호';
COMMENT ON COLUMN AAS_CONCEPT_DESCRIPTION.IS_ACTIVE IS '활성화 여부 (1=활성, 0=비활성)';
COMMENT ON COLUMN AAS_CONCEPT_DESCRIPTION.CD_JSON IS 'ConceptDescription 전체 JSON 데이터';
COMMENT ON COLUMN AAS_CONCEPT_DESCRIPTION.CREATED_BY IS '생성자';
COMMENT ON COLUMN AAS_CONCEPT_DESCRIPTION.CREATED_AT IS '생성 일시';
COMMENT ON COLUMN AAS_CONCEPT_DESCRIPTION.UPDATED_BY IS '수정자';
COMMENT ON COLUMN AAS_CONCEPT_DESCRIPTION.UPDATED_AT IS '수정 일시';
